name: workflow_test

on:
  push:
    branches:
      - '**'          # matches every branch
      - '!main'       # excludes master

jobs: 
  worflow_test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: analizar calidad del codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
      
